// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64          `json:"id"`
	Owner string         `json:"owner"`
	Bio  sql.NullString `json:"bio"`
	Name sql.NullString `json:"name"`
}

type User struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}